# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
zune = "scythe-technology/zune@0.5.2"
lute = "luau-lang/lute@0.1.0-nightly.20251220"
luau-lsp = "johnnymorganz/luau-lsp@1.58.0"
stylua = "johnnymorganz/stylua@2.3.1"
lune = "lune-org/lune@0.10.4"
